// Mock firebase_options.dart for CI build
// Real file should be generated by `flutterfire configure`
// This mock allows CI to build without Firebase setup
// For production, replace with real file from Firebase Console

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // CI Mock - Replace with real values from Firebase Console
  // Firebase Console > Project Settings > Your apps > SDK setup
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'CI_MOCK_WEB_API_KEY',
    appId: '1:123456789:web:abcdef',
    messagingSenderId: '123456789',
    projectId: 'lotofacil-pro-ci',
    authDomain: 'lotofacil-pro-ci.firebaseapp.com',
    storageBucket: 'lotofacil-pro-ci.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'CI_MOCK_ANDROID_API_KEY',
    appId: '1:123456789:android:abcdef',
    messagingSenderId: '123456789',
    projectId: 'lotofacil-pro-ci',
    storageBucket: 'lotofacil-pro-ci.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'CI_MOCK_IOS_API_KEY',
    appId: '1:123456789:ios:abcdef',
    messagingSenderId: '123456789',
    projectId: 'lotofacil-pro-ci',
    storageBucket: 'lotofacil-pro-ci.appspot.com',
    iosBundleId: 'com.berger33.lotofacilpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'CI_MOCK_MACOS_API_KEY',
    appId: '1:123456789:ios:abcdef',
    messagingSenderId: '123456789',
    projectId: 'lotofacil-pro-ci',
    storageBucket: 'lotofacil-pro-ci.appspot.com',
    iosBundleId: 'com.berger33.lotofacilpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'CI_MOCK_WINDOWS_API_KEY',
    appId: '1:123456789:web:abcdef',
    messagingSenderId: '123456789',
    projectId: 'lotofacil-pro-ci',
    authDomain: 'lotofacil-pro-ci.firebaseapp.com',
    storageBucket: 'lotofacil-pro-ci.appspot.com',
  );
}
